### ISSUE TITLE
Bug in BPE

### ISSUE THREAD

**Issue by cpcp1998** [huggingface/tokenizers#643]
It seems that `continuing_subword_prefix` is added for the first character, rather than characters except the first one.
https://github.com/huggingface/tokenizers/blob/ee95e7f0cd0defac6f055d02abd103c40d6c7194/tokenizers/src/models/bpe/model.rs#L339-L345

**Comment by n1t0** [comment]
Can you be more specific? I'm not sure to understand what the bug is, and if there is any.

**Comment by cpcp1998** [comment]
With version 0.10.1, a BPE tokenizer with non-empty `continuing_subword_prefix` behaves strangely. It prepends the prefix to the first subword in a word.
```python
>>> import tokenizers
>>> tokenizers.__version__
'0.10.1'
>>> from tokenizers import Tokenizer
>>> from tokenizers.models import BPE
>>> tokenizer = Tokenizer(BPE(continuing_subword_prefix="##"))
>>> from tokenizers.pre_tokenizers import Whitespace
>>> tokenizer.pre_tokenizer = Whitespace()
>>> from tokenizers.trainers import BpeTrainer
>>> trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], continuing_subword_prefix="##")
>>> tokenizer.train(files=["wiki.train.raw", "wiki.valid.raw", "wiki.test.raw"], trainer=trainer)
[00:00:00] Pre-processing files (13 Mo)             ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                100%
[00:00:00] Tokenize words                           ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 83818    /    83818
[00:00:00] Count pairs                              ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 83818    /    83818
[00:00:03] Compute merges                           ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 28040    /    28040

>>> tokenizer.encode("Hello, y'all! How are you 😁 ?").tokens
['##H', 'e', 'l', 'l', 'o', ',', 'y', "'", '##a', 'l', 'l', '!', '##H', 'o', 'w', '##a', 'r', 'e', '##y', 'o', 'u', '?']
```
It is ok with version 0.8.0.
```python
>>> import tokenizers
>>> tokenizers.__version__
'0.8.0'
>>> from tokenizers import Tokenizer
>>> from tokenizers.models import BPE
>>> tokenizer = Tokenizer(BPE(continuing_subword_prefix="##"))
>>> from tokenizers.pre_tokenizers import Whitespace
>>> tokenizer.pre_tokenizer = Whitespace()
>>> from tokenizers.trainers import BpeTrainer
>>> trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], continuing_subword_prefix="##")
>>> tokenizer.train(files=["wiki.train.raw", "wiki.valid.raw", "wiki.test.raw"], trainer=trainer)
[00:00:00] Reading files (13 Mo)                    ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 100
[00:00:00] Tokenize words                           ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 83818    /    83818
[00:00:00] Count pairs                              ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 83818    /    83818
[00:00:01] Compute merges                           ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 28040    /    28040

>>> tokenizer.encode("Hello, y'all! How are you 😁 ?").tokens
['Hell', '##o', ',', 'y', "'", 'all', '!', 'How', 'are', 'you', '?']
```
These tokenizers are trained on wikitext-2.

**Comment by alexvaca0** [comment]
This is happening to me also, when I train a BPETokenizer, it tokenizes the texts into characters, as for @cpcp1998 

My test script:

```{python}
import glob
import os
import random

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import BpeTrainer

if __name__ == "__main__":
    tokenizer = Tokenizer(BPE())
    tokenizer.pre_tokenizer = Whitespace()
    # tokenizer = ByteLevelBPETokenizer(add_prefix_space=False)

    trainer = BpeTrainer(
        special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"],
        vocab_size=50265,
        continuing_subword_prefix="\u0120",
        min_frequency=1,
    )
    # t = AutoTokenizer.from_pretrained("microsoft/deberta-base")
    files = glob.glob("cleaned_train_data/*.csv")
    files_sample = random.choices(files, k=20)
    data = [
        "Hola me llamo Alejandro",
        "Hola me llamo Alejandro",
        "Hola me llamo Alejandro",
        "Hola me llamo Ramón",
        "Hola me llamo Ramón",
    ] * 2000
    # tokenizer.train(
    #    files=files_sample,
    #    trainer=trainer,
    # )
    tokenizer.train_from_iterator(data, trainer=trainer)
    tokenizer.save("bpe_tokenizer_0903")
```

Then, when I try the tokenizer before saving with the debugger console:

```{python}
out = tokenizer.encode("Hola qué tal")

print(out.tokens)
```
It prints out `['o', 'l', 'a', 'a', 'l']`

**Comment by alexvaca0** [comment]
@n1t0 I've tried installing from the branch you opened to solve this issue (656) and the issue is still present, is there the possibility that the error is not yet solved? (I installed from source because I saw that in your PR all checks had been passed)

**Comment by n1t0** [comment]
I tested your example and added tests to make sure the bug is solved, so I'm pretty sure it works.

In your example you didn't specify the unk_token in BPE, so it just ignores the unknown tokens, which I guess is misleading you.
Can you try to change your BPE for this:
```python
tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
```

**Comment by alexvaca0** [comment]
Are your changes already on master?

**Comment by n1t0** [comment]
No, still on the branch associated to the PR #656.

**Comment by alexvaca0** [comment]
How could I install from there? Because maybe it was my fault that I actually installed from master instead of that branch, as I'm still experiencing the issue. What I did was: 
- git clone repo
- git checkout to the remote branch of the PR
- follow the instructions in Tokenizers documentation for installing from source.

Am I missing something? Thanks for the help :)

**Comment by n1t0** [comment]
Well, it should work then, maybe you should just run `pip uninstall tokenizers` several times in your env to make sure there's no overlapping version installed. I'm merging into `master` now.
